### ISSUE TITLE
Some errors when not installing using ./install.sh

### ISSUE THREAD

**Issue by cwaazywabbit** [sethsec/celerystalk#108]
The following errors are generated when installing from a parent directory and not using `./install.sh`

```
./setup/install.sh 
cp: cannot stat 'config_default.ini': No such file or directory

*************************************************
*        Installing applications via apt        *
*************************************************

[...]

******************************************
* Installing python requirements via pip *
******************************************

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
flag provided but not defined: -version
Usage of /opt/aquatone/aquatone:
[...]
cp: cannot stat 'bash_completion_file': No such file or directory
./setup/install.sh: line 172: ./celerystalk: Is a directory

[...]
```

I think this is mentioned somewhere in the docs, but I'm too lazy to reference it, or was that only about executing `celerystalk` from the directory and not using relative paths? .. anyway :-)

**Comment by sethsec** [comment]
Thanks for submitting this! I've been wanting to fix this for a while. 

I found a way to change to cwd to the directory of the script, which solves the problem. Fixed in Build 206 (https://github.com/sethsec/celerystalk/commit/02d5f5d44bbd23025f6fb61ac0b42204f6765b21) 

You can now run the install script from anywhere :)
